version: 0.2

phases:
  install:
    commands:
      - npm install
  pre_build:
    commands:
      - npm run lint
      # - npm test
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: out

